In [60]:
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt

## 1 задание

In [61]:
AB = np.array([0, 1])
CD = np.array([0, 2])
EF = np.array([0, 3])

In [62]:
N = 100000

In [63]:
F = lambda x: np.prod(x)

In [64]:
points = np.array(list(zip(
    st.uniform.rvs(AB[0], AB[1] - AB[0], N),
    st.uniform.rvs(CD[0], CD[1] - CD[0], N),
    st.uniform.rvs(EF[0], EF[1] - EF[0], N)
)))

In [65]:
np.array([F(point) for point in points]).shape

(100000,)

In [66]:
I = (((AB[1] - AB[0])*(CD[1] - CD[0])*(EF[1] - EF[0]))/N) * np.sum(
    np.array([F(point) for point in points])
)

In [67]:
I

4.510915174158576

## 2 задание

In [366]:
n = 2
A = np.array([
    [0.7, 0.2],
    [0.1, 0.3]
])
B = np.array([0.1, 0.3])
P = np.abs(A) / np.sum(np.abs(A), axis=1).reshape(n, -1)
N = 10000


In [367]:
res = []
for i in range(n):
    x = 0
    w = 1
    index = i
    x += w * B[index]
    for k in range(N):
        chi = np.random.uniform(0, 1)
        j = 0
        while chi > np.sum(P[index, :j+1]):
            j += 1
        w *= np.sign(A[index, j]) * np.sum(np.abs(A)[index])
        x += w * B[j]
        index = j
    res.append(x)
res = np.array(res)

In [368]:
res

array([0.84005848, 0.50620655])

In [369]:
res - (A @ res + B)

array([ 0.05077623, -0.02966126])

## 3 задание

In [248]:
bounds = [
    lambda x: 2 * x[0] ** 2 + x[1] ** 3 - 2,
    lambda x: x[0] + x[1] - 1,
    lambda x: x[0] - 2,
    lambda x: -x[0] - 2,
    lambda x: x[1] - 2,
    lambda x: -x[1] - 2,
]
AB = np.array([-2, 2])
CD = np.array([-2, -1 + np.sqrt(5)])
N = 1000000

In [249]:
def check(point: np.ndarray, bounds):
    return all([f(point) <= 0 for f in bounds])

In [251]:
points = np.array(list(zip(
    st.uniform.rvs(AB[0], AB[1] - AB[0], N),
    st.uniform.rvs(CD[0], CD[1] - CD[0], N),
)))

In [252]:
def square(bounds: list, AB: np.ndarray, CD: np.ndarray, N: int) -> float:
    return (np.sum([check(point, bounds) for point in points])) * (AB[1] - AB[0]) * (CD[1] - CD[0]) / N

In [253]:
square(bounds, AB, CD, N)

6.949481870224618

In [291]:
H = np.array([
    [0.1, 0.45, 0.225],
    [-0.15, 0.1, -0.3],
    [-0.18, 0.36, 0.1]
])
np.abs(H) / np.sum(np.abs(H), axis=1).reshape(3, -1)

array([[0.12903226, 0.58064516, 0.29032258],
       [0.27272727, 0.18181818, 0.54545455],
       [0.28125   , 0.5625    , 0.15625   ]])